dist: xenial
language: python
python:
- '3.6'
- '3.7'
- '3.8'
- '3.9'

install:
- python setup.py install
- pip install Pygments collective.checkdocs

script:
- python setup.py test
- python setup.py checkdocs

after_success:
- bash <(curl -s https://codecov.io/bash)
